#!/bin/bash

fav_nums=(3.14 2.718 .57721 4.6692)

echo "Pi : ${fav_nums[0]}"

fav_nums[4]=1.618

echo "GR : ${fav_nums[4]}"

#echo "Fav_nums : ${fav_nums[*]}"

# Append 1 and 7 to fav_nums w/ +=
fav_nums+=(1 7)

#echo "Fav_nums : ${fav_nums[*]}"

for i in ${fav_nums[*]}; do
	echo $i
done

# Print indexes of fav_num array
for i in ${!fav_nums[@]}; do
	echo "Index : $i"
done

echo "Array Length : ${#fav_nums[@]}"

echo "Index 3 Length: ${#fav_nums[3]}"

sorted_nums=($(for i in "${fav_nums[@]}"; do
	echo $i
done | sort))

for i in ${sorted_nums[*]}; do
	echo $i
done

# Delete item from array
unset 'sorted_nums[1]'

# Delete entire array
unset sorted_nums
