#!/bin/bash

#read -p "Enter 2 Numbers to Sum : " num1 num2

#sum=$((num1+num2))

#echo $sum

read -sp "Enter the secret code" secret

if [ "$secret" == "password" ]; then
	echo "Success"
else 
	echo "Wrong Password"
fi
